### PR TITLE
DevTools Protocol

### PR DESCRIPTION
**Pull request by davidkpiano**
[View rendered text](https://github.com/statelyai/rfcs/blob/davidkpiano/devtools-protocol/text/0000-devtools-protocol.md)

### CODE REVIEW

**Comment by tom-sherman** [comment]
Can this help with inspecting a service with hundreds of actors? The inspector takes absolutely forever to start up in this case at the moment

**Comment by davidkpiano** [comment]
> Can this help with inspecting a service with hundreds of actors? The inspector takes absolutely forever to start up in this case at the moment

That's a good consideration - can you identify specifically what the bottleneck is?

**Comment by tom-sherman** [comment]
I'll take a look tomorrow, I'm sure a repro would be straight forward.

**Comment by tom-sherman** [comment]
Look like the bottleneck right now is that a message is sent for each actor. This RFC appears to solve the issue via the `@xstate/inspect.actors` event - cool!

**Comment by davidkpiano** [comment]
Notes from @Andarist:

- Need a way for the client to request actor snapshots from inspector at any time
- Need to persist events (perhaps with a configurable limit)

**Comment by davidkpiano** [comment]
TODO: consider a "restart" event that the inspector can send the client for individual actors? cc. @farskid

**Comment by SimeonC** [comment]
This looks great. I think the notes that @Andarist made are important for the implementation I made for storybook - particularly `Need a way for the client to request actor snapshots from inspector at any time`. Putting the inspector in as a storybook addon requires use of the storybook “message bus” to get from the iframe with running machines to the iframe that the devtools are loaded in, which is in essence another postmessage system. This indirection leads to very long startup times for the addon as I have to make sure that everything is started up in sequence meaning that sometimes I can’t catch the first few events on startup.

one other thing I did in the addon was to alter the default of devTools as passed to inspect here: https://github.com/SimeonC/storybook-xstate-addon/blob/main/src/preset/withXstateInspector.ts#L18

**Review by davidkpiano — COMMENTED** [review]
Update `InspectedEventObject` and add `XStateInspectMessageEvent`

**Pull request merged**
